config/routes.rb
SkytrainApp::Application.routes.draw do
  
  resources :restaurants
  resources :shops 
  resources :attractions 
  resources :stations, only: [:index, :show]
  resources :trainlines, only: [:index, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'trainlines#index'

  

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base

  belongs_to :station

  validates :name,
    presence: true

  validates :longitude,
    presence: true

  validates :latitude,
    presence: true

  validates :description,
    presence: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  before_create :set_paid_at
  after_create :send_receipt_email

  belongs_to :subscription

  validates :subscription_id,
    presence: true

  validates :amount,
    presence: true,
    numericality: true

  validates :paid_at,
    presence: true

  def set_paid_at
  end

  def send_receipt_email
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  belongs_to :station

  validates :name,
    presence: true

  validates :longitude,
    presence: true

  validates :latitude,
    presence: true

  validates :cuisine,
    presence: true
    
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  
  belongs_to :station

  validates :name,
    presence: true

  validates :longitude,
    presence: true

  validates :latitude,
    presence: true

  validates :type,
    presence: true

end

app/models/station.rb
class Station < ActiveRecord::Base

  has_many :station_trainlines
  has_many :trainlines, through: :station_trainlines

  validates :name,
    presence: true

  validates :longitude,
    presence: true

  validates :latitude,
    presence: true

  validates :neighbourhood,
    presence: true

  validates :sequence_num,
    presence: true 

  def get_the_next_station
    station = Station.find_by_sequence_num(self.sequence_num + 1)
  end

end

app/models/station_trainline.rb
class StationTrainline < ActiveRecord::Base

  belongs_to :station
  belongs_to :trainline

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :user
  has_many :payments

  scope :requires_rebill, -> { where("last_payment_date <= :one_month_ago", { one_month_ago: Date.today.advance(months: -1) } ) }

  validates :user_id,
    presence: true

  validates :start_date,
    presence: true

  validates :next_payment_date,
    presence: true

  validates :last_payment_date,
    presence: true
    
end

app/models/trainline.rb
class Trainline < ActiveRecord::Base

  has_many :station_trainlines
  has_many :stations, through: :station_trainlines

  validates :name,
    presence: true

  # def superAwesomeHappyFunTimes a 
  #   if (a == 2)
  #     "blah"
  #   elsif (a == 1)
  #     "YAY!!!!!"
  #   else
  #     "wow that's another number"
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :trainlines
  has_many :stations
  has_one :subscription

  has_secure_password

  validates :email,
    presence: true,
    uniqueness: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: {in: 5..20}, on: :create

  validates :card_info,
    presence: true, if: :subscribed?

  validates :name_on_card,
    presence: true, if: :subscribed?

  validates :expiration_month,
    presence: true, if: :subscribed?

  validates :expiration_year,
    presence: true, if: :subscribed?

  def full_name
    "#{firstname} #{lastname}".strip
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restricted_access
    if !current_user
      flash[:alert] = "You must log in"
      redirect_to new_sessions_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to trainlines_path, notice: "Welcome back, #{user.firstname}"
    else
      flash.now[:alert] = "Log in failed. Please try again"
      render :new
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to trainlines_path, notice: "See you again."
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  
  def index
    @shops = Shop.all
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
  end

  def show
    @station     = Station.find(params[:id])
    @attractions = Attraction.all
  end
  
end

app/controllers/trainlines_controller.rb
class TrainlinesController < ApplicationController
  
  def index
    @trainlines = Trainline.all
  end

  def show
    @trainline = Trainline.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to trainlines_path, notice: "Welcome #{@user.firstname}"
    else
      render :new
    end
  end  

  protected

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trainlines_helper.rb
module TrainlinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>

app/views/stations/_station.html.erb
<li>
  <%= 
</li>

app/views/stations/index.html.erb
<h1>Stations#index</h1>
<%= link_to "Back to all Trainlines", trainlines_path %><br/>
<hr>
<% @stations.each do |station| %>
  <%= link_to station.name, station_path(station) %>
<br>
<% end %>

app/views/stations/show.html.erb
<h1><%= @station.name %></h1>
<%= link_to "Back to all Stations", stations_path %> | <%= link_to "Back to all Trainlines", trainlines_path %><br/>
<hr>
<h2>Location:</h2>
<div class ="googlemap">
<iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.ca/maps?hl=en&amp;ie=UTF8&amp;t=m&amp;ll=49.286395,-123.11202&amp;spn=0.006718,0.013733&amp;z=16&amp;output=embed"></iframe><br /><small><a href="https://maps.google.ca/maps?hl=en&amp;ie=UTF8&amp;t=m&amp;ll=49.286395,-123.11202&amp;spn=0.006718,0.013733&amp;z=16&amp;source=embed" style="color:#0000FF;text-align:right">View Larger Map</a></small></div>
<h2>Description:</h2>
<p>This is where the biography of the station goes. It was named after Person A and serves as one of the many entrances from suburb city into the downtown core.</p>
<h2>Attractions:</h2>
<%= render @attractions %>
<h2>Retailers:</h2>
<h2>Restaurants:</h2>

<!-- for each attr in attractions
  render attr, locals: attr  -->

app/views/trainlines/_form.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/trainlines/index.html.erb
<h1>Skytrain Lines</h1>
<hr>
<% @trainlines.each do |trainline| %>
  <%= link_to trainline.name, trainline_path(trainline) %>
<br>
<% end %>

app/views/trainlines/show.html.erb
<h1>Stations</h1>
<%= link_to "Back to all Trainlines", trainlines_path %><br/>
<hr>
<% @trainline.stations.each do |station| %>
  <%= link_to station.name, station_path(station.id) %> 
<br> 
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= link_to "Back to Trainlines", trainlines_path %>
<hr>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>